project:
  type: website

website:
  title: "Alex Raeside - Bioinformatics"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: united
    css: styles.css

editor: visual

